// anf-rs/apps/frontend/src/pages/HomePage.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { getAdapter, type ComicSnapshot } from '@/api'
import { useAppStore } from '@/stores/app'
import ComicCard from '@/components/ComicCard.vue'

const router = useRouter()
const store = useAppStore()
const proposals = ref<ComicSnapshot[]>([])
const proposalLoading = ref(false)

onMounted(async () => {
  proposalLoading.value = true
  try {
    const adapter = await getAdapter()
    proposals.value = await adapter.getProposal(undefined, 12)
  } catch (e) {
    console.error(e)
  } finally {
    proposalLoading.value = false
  }
})

async function handleSearch() {
  if (!store.keyword.trim()) return
  store.setSearching(true)
  try {
    const adapter = await getAdapter()
    const result = await adapter.search(store.keyword)
    store.setSearchResults(result.snapshots)
  } catch (e) {
    console.error(e)
  } finally {
    store.setSearching(false)
  }
}

function handleClick(snap: ComicSnapshot) {
  const url = snap.sources[0]?.target_url || snap.target_url
  router.push(`/comic?url=${encodeURIComponent(url)}`)
}
</script>

<template>
  <div class="home">
    <div class="search-bar">
      <va-input
        v-model="store.keyword"
        placeholder="Search comics or paste a URL..."
        @keyup.enter="handleSearch"
        class="search-input"
      >
        <template #append>
          <va-button
            :loading="store.searching"
            icon="search"
            @click="handleSearch"
          />
        </template>
      </va-input>
    </div>

    <div v-if="store.searchResults.length > 0">
      <h3 class="section-title">Search Results</h3>
      <div class="comic-grid">
        <ComicCard
          v-for="(snap, i) in store.searchResults"
          :key="i"
          :snapshot="snap"
          @click="handleClick(snap)"
        />
      </div>
    </div>

    <div v-else>
      <h3 class="section-title">Proposals</h3>
      <va-inner-loading :loading="proposalLoading">
        <div class="comic-grid">
          <ComicCard
            v-for="(snap, i) in proposals"
            :key="i"
            :snapshot="snap"
            @click="handleClick(snap)"
          />
        </div>
      </va-inner-loading>
    </div>
  </div>
</template>

<style scoped>
.home {
  max-width: 1000px;
  margin: 0 auto;
}

.search-bar {
  margin-bottom: 2rem;
}

.search-input {
  width: 100%;
}

.section-title {
  color: var(--va-text-secondary);
  margin-bottom: 1rem;
}

.comic-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
  gap: 1rem;
}
</style>

// anf-rs/apps/anf-tauri/frontend/src/pages/HomePage.tsx
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Search as SearchIcon, Loader2 } from "lucide-react";
import { useStore } from "../store";
import { search as searchApi, getProposal, type ComicSnapshot } from "../api";
import ComicCard from "../components/ComicCard";

export default function HomePage() {
  const navigate = useNavigate();
  const { keyword, setKeyword, searchResults, setSearchResults, searching, setSearching } = useStore();
  const [proposals, setProposals] = useState<ComicSnapshot[]>([]);
  const [proposalLoading, setProposalLoading] = useState(false);

  useEffect(() => {
    setProposalLoading(true);
    getProposal(undefined, 10).then(setProposals).catch(console.error).finally(() => setProposalLoading(false));
  }, []);

  const handleSearch = async () => {
    if (!keyword.trim()) return;
    setSearching(true);
    try {
      const result = await searchApi(keyword);
      setSearchResults(result.snapshots);
    } catch (e) { console.error(e); }
    finally { setSearching(false); }
  };

  const handleClick = (snap: ComicSnapshot) => {
    const url = snap.sources[0]?.target_url || snap.target_url;
    navigate(`/comic?url=${encodeURIComponent(url)}`);
  };

  const showResults = searchResults.length > 0;

  return (
    <div className="max-w-6xl mx-auto p-4">
      <div className="flex gap-2 mb-6">
        <input
          value={keyword}
          onChange={(e) => setKeyword(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && handleSearch()}
          placeholder="Search comics or paste a URL..."
          className="flex-1 px-4 py-2 bg-gray-800 border border-gray-700 rounded-lg focus:outline-none focus:border-emerald-500"
        />
        <button onClick={handleSearch} disabled={searching}
          className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 rounded-lg disabled:opacity-50 flex items-center gap-2">
          {searching ? <Loader2 className="animate-spin" size={16} /> : <SearchIcon size={16} />}
          Search
        </button>
      </div>

      {showResults ? (
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
          {searchResults.map((snap, i) => (
            <ComicCard key={i} snapshot={snap} onClick={() => handleClick(snap)} />
          ))}
        </div>
      ) : (
        <div>
          <h2 className="text-lg font-semibold mb-4 text-gray-400">Proposals</h2>
          {proposalLoading ? (
            <div className="flex justify-center py-12"><Loader2 className="animate-spin text-emerald-400" size={32} /></div>
          ) : (
            <div className="flex gap-4 overflow-x-auto pb-4">
              {proposals.map((snap, i) => (
                <ComicCard key={i} snapshot={snap} onClick={() => handleClick(snap)} wide />
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
